apiVersion: batch/v1
kind: CronJob
metadata:
  name: watchlist-slack-bot
  labels:
    app: watchlist-slack-bot
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: watchlist-slack-bot
        spec:
          containers:
          - name: watchlist-slack-bot
            image: australia-southeast2-docker.pkg.dev/${GCP_PROJECT}/cmek-container-images/watchlist-slack-bot:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: watchlist-slack-bot
          restartPolicy: OnFailure
