name: Call Push OCI to GAR

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'infra/k8s/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'infra/k8s/**'
  workflow_dispatch:

jobs:
  generate-build-id:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

  call-push-oci-gar:
    needs: generate-build-id
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/flux_k8s_manifests_oci_push_to_gar.yaml@main
    with:
      app_name: watchlist-slack-bot
      build_id: ${{ needs.generate-build-id.outputs.BUILD_ID }}
    secrets: inherit
