name: Call Push OCI to GAR

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'infra/k8s/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'infra/k8s/**'
  workflow_dispatch:

jobs:
  call-push-oci-gar:
    env:
      OCI_REPO_NAME: "oci://${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/manifests/${{ secrets.APP_NAME }}"
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/k8s_oci_gar.yaml@main
    with:
      oci_repo_name: ${{ env.OCI_REPO_NAME }}
    secrets: inherit
