name: docker

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'requirements.txt'
      - '*.py'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'requirements.txt'
      - '**.py'
      
  workflow_dispatch:

jobs:
  build-push:
    env:
        IMAGE: andreistefanciprian/watchlist-slack-bot
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"          
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: ./infra/Dockerfile
        tags: |
          ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}  